name: aacautoupdate # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Manages updating the Adopt-a-Cell web app. # 79 char long summary
description: |
  This snap is a server-side automatic updater for the UMN SVP Adopt-a-Cell
  interactive graphic web app. It periodically checks if any new people have
  donated enough to have a cell in their name and updates the web app as needed.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  aacautoupdate:
    after: [go]
    source: .
    plugin: go
    go-importpath: github.com/iAmSomeone2/aacautoupdate

apps:
  aacautoupdate:
    command: aacautoupdate
