name: aacautoupdate # you probably want to 'snapcraft register <name>'
title: Adopt-a-Cell Auto Updater
base: core18 # the base snap is the execution environment for this snap
version: 0.1+git # just for humans, typically '1.2+git' or '1.3.2'
summary: Manages updating the Adopt-a-Cell web app. # 79 char long summary
description: |
  This snap is a server-side automatic updater for the UMN SVP Adopt-a-Cell
  interactive graphic web app. It periodically checks if any new people have
  donated enough to have a cell in their name and updates the web app as needed.
license: MIT
type: app

icon: icons/icon.svg

architectures:
  - build-on: [amd64, arm64]
    run-on: [amd64, arm64]

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  aacautoupdate:
    source: .
    plugin: go
    go-channel: 1.12/stable
    go-importpath: github.com/iAmSomeone2/aacautoupdate
    build-packages:
      - g++
      - gcc


apps:
  aacautoupdate:
    command: aacautoupdate
    daemon: simple
    restart-condition: on-failure
