name: aacautoupdate 
title: Adopt-a-Cell Auto Updater
base: core18
version: '1.0'
adopt-info: aacautoupdate
  
license: MIT
type: app

architectures:
  - build-on: [amd64, i386, arm64, armhf]
    run-on: [amd64, i386, arm64, armhf]


grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

# We're going to try to bind the 'data' directory of the website into the snap.
#layout:
#  /var/www/cell.bdavidson.dev/html/data:
#    bind: $SNAP_DATA/var/www/cell.bdavidson.dev/html/data

apps:
  aacautoupdate:
    command: bin/aacautoupdate -cleanrun
    daemon: simple
    restart-condition: on-failure

parts:
  aacautoupdate:
    parse-info: [aacautoupdate.metainfo.xml]
    source: .
    plugin: go
    go-channel: 1.12/stable
    go-importpath: github.com/iAmSomeone2/aacautoupdate
    build-packages:
      - git
      - gcc
